version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     networks:
       - blog_database

   wordpress:
     image: wordpress:latest
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     deploy:
       labels:
         - 'traefik.docker.network.name=prod_gateway'
         - "traefik.frontend.rule=Host:blog.communitygrid.dms.local,blog.communitygrid.dallasmakerspace.org"
         - "traefik.frontend.priority=0"
         - "traefik.enable=true"
         - "traefik.port=80"
         - "traefik.docker.network=CommunityGrid_gateway"
         - "traefik.acme.domains=blog.communitygrid.dallasmakerspace.org"
         - "com.centurylinklabs.watchtower.enable"
     networks:
       - prod_gateway
       - blog_database

networks:
    prod_gateway:
    blog_database:

volumes:
    db_data:
